@startuml

top to bottom direction
!define BACKGROUND_COLOR white
skinparam backgroundColor BACKGROUND_COLOR
actor Atendente as Atend
actor Caixa as Caixa
actor Cliente as Cli
Atend <|-- Caixa #orange;line:orange;line.bold;text:orange
rectangle "SISTEMA DE COMPRA DE MATERIA PRIMA - SCMP" as Sistema #white;line:black;line.bold;text:black; {
usecase "Atender Cliente" as At
usecase "Consultar Estoque" as Card
usecase "Solicitar Ferramenta" as Sol
usecase "Aguardar Entrega" as Ag
usecase "Pegar o produto" as Prod
usecase "Entregar Ferramenta" as Ent
usecase/ (Pagar) as Pag
}
Cli -right- Ag #blue;line:blue;line.bold;text:blue
Cli -right- Prod #blue;line:blue;line.bold;text:blue
Cli -right- Pag #blue;line:blue;line.bold;text:blue
Cli -right- Sol #blue;line:blue;line.bold;text:blue
Ag ..> Sol #red;line:red;text:red : <extends>
Atend -right- Card #blue;line:blue;line.bold;text:blue
Atend -left- Ent #blue;line:blue;line.bold;text:blue
(At) <|-- (Ent) #orange;line:orange;line.bold;text:orange
Caixa -left- Pag #blue;line:blue;line.bold;text:blue
Atend -left- At #blue;line:blue;line.bold;text:blue
Sol ..> Card #red;line:red;text:red : <Include>
@enduml
