@startuml casodeUso
    left to right direction

    actor "Cliente" as Cl
    actor "Atendente" as Att
    actor "Estoquista" as Etq
    rectangle Loja_de_Ferramentas {
        usecase "Consultar ferramentas" as UC1
        usecase "Solicita a Ferramenta" as UC2
        usecase "Paga a Ferramenta" as UC3
        usecase "Recebe a Compra" as UC4
        usecase "Atende o Cliente" as UC5
        usecase "Requerir a ferramenta" as UC6
        usecase "Entrega a ferramenta" as UC7
        usecase "Verifica o Estoque" as UC8
        usecase "Pega a ferramenta" as UC9
        usecase "Encerra a compra" as UC10

        Cl -- UC1
        Att <--> Cl
        Att <--> Etq
        Att --UC5
        Etq -- UC8
        UC1 -- UC2
        UC2 -- UC3
        UC3 -- UC4
        UC5 -- UC6
        UC6 -- UC7
        UC8 -- UC9
        UC9 -- UC7
        UC7 -- UC4
        UC4 -- UC10


    }

@enduml